/* eslint-disable */
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvanceCleanLand: typeof import('./../components/business/collection-access/advance-clean-land.vue')['default']
    ChartAnnotation: typeof import('./../components/business/monitor-echarts/components/chart-annotation.vue')['default']
    ChartLegend: typeof import('./../components/business/monitor-echarts/components/chart-legend.vue')['default']
    ChartMenu: typeof import('./../components/business/monitor-echarts/components/chart-menu.vue')['default']
    ChartTitle: typeof import('./../components/business/monitor-echarts/components/chart-title.vue')['default']
    ChartTitleNew: typeof import('./../components/business/monitor-echarts/components/chart-title-new.vue')['default']
    ChartTitleOld: typeof import('./../components/business/monitor-echarts/components/chart-title-old.vue')['default']
    ChartTitleV2: typeof import('./../components/business/monitor-echarts/components/chart-title-v2.vue')['default']
    ChartTools: typeof import('./../components/business/monitor-echarts/components/chart-tools.vue')['default']
    ClusterTable: typeof import('./../components/business/collection-access/components/cluster-table.vue')['default']
    CollectionAccess: typeof import('./../components/business/collection-access/index.vue')['default']
    ConfigLogSetEditItem: typeof import('./../components/business/collection-access/components/step-add/config-log-set-edit-item.vue')['default']
    ConfigLogSetItem: typeof import('./../components/business/collection-access/components/step-add/config-log-set-item.vue')['default']
    ConfigsSelect: typeof import('./../components/business/collection-access/components/step-add/configs-select.vue')['default']
    ConfigViewDialog: typeof import('./../components/business/collection-access/components/step-add/config-view-dialog.vue')['default']
    ContainerTargetItem: typeof import('./../components/business/collection-access/components/step-add/container-target-item.vue')['default']
    DeviceMetadata: typeof import('./../components/business/collection-access/components/step-add/device-metadata.vue')['default']
    FieldTable: typeof import('./../components/business/collection-access/field-table.vue')['default']
    IssuedSlider: typeof import('./../components/business/collection-access/issued-slider.vue')['default']
    LabelTargetDialog: typeof import('./../components/business/collection-access/components/step-add/label-target-dialog.vue')['default']
    LogView: typeof import('./../components/business/log-view/index.vue')['default']
    MatchLabel: typeof import('./../components/business/collection-access/components/step-add/match-label.vue')['default']
    MatchLabelItem: typeof import('./../components/business/collection-access/components/step-add/match-label-item.vue')['default']
    MonacoEditor: typeof import('./../components/business/collection-access/components/step-add/monaco-editor.vue')['default']
    MonitorEchartsNew: typeof import('./../components/business/monitor-echarts/monitor-echarts-new.vue')['default']
    MultilineRegDialog: typeof import('./../components/business/collection-access/components/step-add/multiline-reg-dialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusChart: typeof import('./../components/business/monitor-echarts/components/status-chart.vue')['default']
    StepAdd: typeof import('./../components/business/collection-access/step-add.vue')['default']
    StepCapacity: typeof import('./../components/business/collection-access/step-capacity.vue')['default']
    StepField: typeof import('./../components/business/collection-access/step-field.vue')['default']
    StepIssued: typeof import('./../components/business/collection-access/step-issued.vue')['default']
    StepResult: typeof import('./../components/business/collection-access/step-result.vue')['default']
    StepStorage: typeof import('./../components/business/collection-access/step-storage.vue')['default']
    TextChart: typeof import('./../components/business/monitor-echarts/components/text-chart.vue')['default']
    TrendChart: typeof import('./../components/business/monitor-echarts/trend-chart.vue')['default']
    YamlEditor: typeof import('./../components/business/collection-access/components/step-add/yaml-editor.vue')['default']
  }
}
