#!/bin/bash
# BKLog Web-V3 组件迁移助手脚本

OLD_SRC="/root/clawd/bk-monitor/bklog/web/src"
NEW_SRC="/root/clawd/bk-monitor/bklog/web/packages/web-v3/src"

echo "=========================================="
echo "BKLog Web-V3 组件迁移助手"
echo "=========================================="
echo ""

# 创建必要的目录结构
echo "创建目录结构..."
mkdir -p "$NEW_SRC/components/business"
mkdir -p "$NEW_SRC/components/common"
mkdir -p "$NEW_SRC/components/dialog"
mkdir -p "$NEW_SRC/components/form"
mkdir -p "$NEW_SRC/components/nav"
mkdir -p "$NEW_SRC/components/table"
mkdir -p "$NEW_SRC/components/charts"
mkdir -p "$NEW_SRC/components/collection"
mkdir -p "$NEW_SRC/components/masking"
mkdir -p "$NEW_SRC/components/rule"

echo "✓ 目录结构创建完成"
echo ""

# 列出待迁移的组件
echo "待迁移组件清单:"
echo ""
echo "基础组件 (7个):"
echo "  [ ] log-button"
echo "  [ ] log-icon"
echo "  [ ] empty-status"
echo "  [ ] basic-tab"
echo "  [ ] bklog-popover"
echo "  [ ] step-box"
echo "  [ ] ellipsis-tag-list"
echo ""
echo "对话框组件 (2个):"
echo "  [ ] global-dialog"
echo "  [ ] global-setting"
echo ""
echo "导航组件 (2个):"
echo "  [ ] manage-nav"
echo "  [ ] top-nav"
echo ""
echo "表单组件 (5个):"
echo "  [ ] time-range"
echo "  [ ] user-selector"
echo "  [ ] ip-select"
echo "  [ ] log-ip-selector"
echo "  [ ] index-set-label-select"
echo ""
echo "=========================================="
echo "使用提示："
echo "1. 每个组件迁移后创建 .tsx 文件"
echo "2. 使用 Vue3 Composition API + TSX"
echo "3. 替换 bkui-vue 为 TDesign"
echo "4. 添加完整的 TypeScript 类型"
echo "5. 更新 COMPONENT_MIGRATION_PROGRESS.md"
echo "=========================================="
